export const LOGIN_REQUEST = 'LOGIN'
export const LOGIN_SUCCESS =  'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOG_OUT = 'LOG_OUT'

export const UPLOAD_FILE = 'UPLOAD_FILE'
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED'



export const REGISTER_REQUEST = 'REGISTER'
export const REGISTER_SUCCESS =  'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'
 


export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAILED = 'GET_ALL_PRODUCTS_FAILED'



